/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_db_KVleveldb */

#ifndef _Included_com_yahoo_ycsb_db_KVleveldb
#define _Included_com_yahoo_ycsb_db_KVleveldb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_ycsb_db_KVleveldb_init
  (JNIEnv *, jobject);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_ycsb_db_KVleveldb_close
  (JNIEnv *, jobject);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    getBatchSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_db_KVleveldb_getBatchSize
  (JNIEnv *, jobject);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    get
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_yahoo_ycsb_db_KVleveldb_get
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    insert
 * Signature: ([BI[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_ycsb_db_KVleveldb_insert
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    update
 * Signature: ([BI[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_ycsb_db_KVleveldb_update
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    delete
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_ycsb_db_KVleveldb_delete
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_yahoo_ycsb_db_KVleveldb
 * Method:    writeBatch
 * Signature: (Lcom/yahoo/ycsb/db/WriteBatch;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_ycsb_db_KVleveldb_writeBatch
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
