/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_db_ReadOptions */

#ifndef _Included_com_yahoo_ycsb_db_ReadOptions
#define _Included_com_yahoo_ycsb_db_ReadOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_ycsb_db_ReadOptions
 * Method:    init
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_ReadOptions_init
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_yahoo_ycsb_db_ReadOptions
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_ReadOptions_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
