/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_db_ReadOptionsV2 */

#ifndef _Included_com_yahoo_ycsb_db_ReadOptionsV2
#define _Included_com_yahoo_ycsb_db_ReadOptionsV2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_ycsb_db_ReadOptionsV2
 * Method:    init
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_ReadOptionsV2_init
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_yahoo_ycsb_db_ReadOptionsV2
 * Method:    setscan
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_ReadOptionsV2_setscan
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yahoo_ycsb_db_ReadOptionsV2
 * Method:    setpack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_ReadOptionsV2_setpack
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yahoo_ycsb_db_ReadOptionsV2
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_ReadOptionsV2_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
